project:
  type: website
  output-dir: docs
website:
  title: "Mert's Learning Journal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mkobas18
      - icon: twitter
        href: https://twitter.com/mertkobas
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

